
language = {
    'ptbr': {

            #MAIN MENU
        'PARKING SYS': '[blue]SISTEMA de ESTACIONAMENTO[/]',
        'REGISTER_VEHICLE': 'REGISTRAR VEÍCULO',
        'REGISTER_EXIT': 'REGISTRAR SAÍDA',
        'SHOW_QUANTITY': 'VER QUANTIDADE',
        'SHOW _REGISTERS': 'MOSTRAR REGISTROS',
        'CHANGE_LANGUAGE': 'ALTERAR IDIOMA',


        #REGISTER MENU
        'ENTRANCE': 'ENTRADA',
        'VEHICLES': 'VEÍCULOS',
        'VEHICLES ENTRANCE': 'ENTRADA DE VEÍCULOS',
        'VEHICLES EXIT':'SAÍDA DE VEÍCULOS',
        'TIME': 'HORÁRIO',
        'PLATE': 'PLACA',
        #REGISTER MESSAGE
        'REGISTRATION_SUCCESSFULLY_COMPLETED': '[bright_white]REGISTRO REALIZADO COM[/] [green3]SUCESSO[/]',
        'REGISTER_AGAIN': 'REGISTRAR NOVAMENTE?',


        #ENTRANCE MENU
        'ENTRY_TIME': 'HORÁRIO DE ENTRADA',
        'INVALID_TIME': 'HORÁRIO INVÁLIDO (HH:MM)',


        # EXIT MENU
        'EXIT': 'SAÍDA',
        'EXIT_TIME': 'HORÁRIO DE SAÍDA',
        'TOTAL_TIME': 'TEMPO TOTAL',


        # SHOW_REGISTERS MENU
        'SHOW_REGISTER': 'MOSTRAR REGISTROS',
        'SEE_QUANTITY': 'VER QUANTIDADE',
        'REGISTERED_VEHICLES': 'VEÍCULOS REGISTRADOS',

        #MESSAGES
        'INVALID_NUM_ERROR': 'NÚMERO INVÁLIDO',
        'INVALID_PLATE_ERROR': 'PLACA INVÁLIDA',
        'INVALID_OPTION_ERROR': 'OPÇÃO INVÁLIDA',
        'NO_PLATE': 'NENHUMA PLACA REGISTRADA',
        'NO_REGISTERED_VEHICLE': 'NENHUM VEÍCULO REGISTRADO',
        'TYPE_MORE_CHARACTERS': 'VÁRIOS VEÍCULOS ENCONTRADOS. DIGITE MAIS CARACTERES',
        'VEHICLE_NOT_FOUND': 'VEÍCULO NÃO ENCONTRADO',
        'VEHICLE_FOUND': 'VEÍCULO ENCONTRADO',
        'TAX_VALUE': 'VALOR A SER PAGO'

    },
}
