
language = {
    'ptbr': {

            #MAIN MENU
        'PARKING SYS': '[blue]SISTEMA de ESTACIONAMENTO 10ka[/]',
        'REGISTER_VEHICLE': 'REGISTRAR VEÍCULO',
        'REGISTER_EXIT': 'REGISTRAR SAÍDA',
        'SHOW_REGISTERS': 'MOSTRAR/EDITAR REGISTROS',
        'CHANGE_LANGUAGE': 'ALTERAR IDIOMA',


        #REGISTER MENU
        'ENTRANCE': 'ENTRADA',
        'VEHICLES': 'VEÍCULOS',
        'VEHICLES ENTRANCE': 'ENTRADA DE VEÍCULOS',
        'VEHICLES EXIT':'SAÍDA DE VEÍCULOS',
        'TIME': 'HORÁRIO',
        'PLATE': 'PLACA',
        #REGISTER MESSAGE
        'REGISTRATION_SUCCESSFULLY_COMPLETED': '[bright_white]REGISTRO REALIZADO COM[/] [green3]SUCESSO[/]',
        'REGISTER_AGAIN': 'REGISTRAR NOVAMENTE?',


        #ENTRANCE MENU
        'ENTRY_TIME': 'HORÁRIO DE ENTRADA',
        'INVALID_TIME': 'HORÁRIO INVÁLIDO (HH:MM)',


        # EXIT MENU
        'EXIT': 'SAÍDA',
        'EXIT_TIME': 'HORÁRIO DE SAÍDA',
        'TOTAL_TIME': 'TEMPO TOTAL',


        # SHOW_REGISTERS MENU
        'SHOW_REGISTER': 'MOSTRAR REGISTROS',
        'REGISTERED_VEHICLES': 'VEÍCULOS REGISTRADOS',
        'WANNA_CHANGE_VEHICLE': 'DESEJA EDITAR O VEÍCULO?',


        #MESSAGES
        'INVALID_NUM_ERROR': 'NÚMERO INVÁLIDO',
        'INVALID_PLATE_ERROR': 'PLACA INVÁLIDA',
        'INVALID_OPTION_ERROR': 'OPÇÃO INVÁLIDA',
        'NO_PLATE': 'NENHUMA PLACA REGISTRADA',
        'NO_REGISTERED_VEHICLE': 'NENHUM VEÍCULO REGISTRADO',
        'TYPE_MORE_CHARACTERS': 'VÁRIOS VEÍCULOS ENCONTRADOS. DIGITE MAIS CARACTERES',
        'VEHICLE_NOT_FOUND': 'VEÍCULO NÃO ENCONTRADO',
        'VEHICLE_FOUND': 'VEÍCULO ENCONTRADO',
        'TAX_VALUE': 'VALOR A SER PAGO',


        #DATA
        'SUCCESSFULLY_SAVED': '[green]DADOS SALVOS COM SUCESSO[/]'

    },

    'en': {

                #MAIN MENU
            'PARKING SYS': '[blue]10ka PARKING SYSTEM[/]',
            'REGISTER_VEHICLE': 'REGISTER VEHICLE',
            'REGISTER_EXIT': 'REGISTER EXIT',
            'SHOW_REGISTERS': 'SHOW/EDIT REGISTERS',
            'CHANGE_LANGUAGE': 'CHANGE LANGUAGE',


            #REGISTER MENU
            'ENTRANCE': 'ENTRY',
            'VEHICLES': 'VEHICLES',
            'VEHICLES ENTRANCE': 'VEHICLE ENTRIES',
            'VEHICLES EXIT':'VEHICLE EXITS',
            'TIME': 'TIME',
            'PLATE': 'LICENSE PLATE',
            #REGISTER MESSAGE
            'REGISTRATION_SUCCESSFULLY_COMPLETED': '[bright_white]REGISTRATION COMPLETED[/] [green3]SUCCESSFULLY[/]',
            'REGISTER_AGAIN': 'REGISTER ANOTHER VEHICLE?',


            #ENTRANCE MENU
            'ENTRY_TIME': 'ENTRY TIME',
            'INVALID_TIME': 'INVALID TIME (HH:MM)',


            # EXIT MENU
            'EXIT': 'EXIT',
            'EXIT_TIME': 'EXIT TIME',
            'TOTAL_TIME': 'TOTAL TIME',


            # SHOW_REGISTERS MENU
            'SHOW_REGISTER': 'VIEW RECORDS',
            'REGISTERED_VEHICLES': 'REGISTERED VEHICLES',
            'WANNA_CHANGE_VEHICLE': 'EDIT THIS VEHICLE?',


            #MESSAGES
            'INVALID_NUM_ERROR': 'INVALID NUMBER',
            'INVALID_PLATE_ERROR': 'INVALID LICENSE PLATE',
            'INVALID_OPTION_ERROR': 'INVALID OPTION',
            'NO_PLATE': 'NO LICENSE PLATE REGISTERED',
            'NO_REGISTERED_VEHICLE': 'NO REGISTERED VEHICLES',
            'TYPE_MORE_CHARACTERS': 'MULTIPLE VEHICLES FOUND. TYPE MORE CHARACTERS',
            'VEHICLE_NOT_FOUND': 'VEHICLE NOT FOUND',
            'VEHICLE_FOUND': 'VEHICLE FOUND',
            'TAX_VALUE': 'AMOUNT TO PAY',


            #DATA
            'SUCCESSFULLY_SAVED': '[green]DADOS SALVOS COM SUCESSO[/]'
    }
}
